services:
  postgres_sorteador_db_live:
    image: postgres
    container_name: postgres_sorteador_db_live
    restart: always
    ports:
      - 4457:5432
    env_file:
      - ./back-end/.env.test

  node_sorteador_app_live:
    container_name: node_sorteador_app_live
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres_sorteador_db_live
    env_file:
      - ./back-end/.env.test