on:
  push:
    branches:
      - main

name: Build and Deploy
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          drivenops-project23_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          drivenops-project23_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          drivenops-project23_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          drivenops-project23_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end/
          file_name: .env
          fail_on_empty: true

      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          drivenops-project23_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
          directory: front-end/
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up -d
